# Generated by Django 2.2.18 on 2022-01-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20220110_1159'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Participant',
            new_name='Participants',
        ),
    ]
